### ISSUE TITLE
[BUG] Not Receiving Person-to-Person BANK Transactions properly

### ISSUE THREAD

**Issue by Person-AL767** [xXJamieXx/paradox-bugs#199]
**Your Discord Name**
Person__AL
**Describe the bug**

Cannot receive bank transactions from people paying via Maze Bank app. 

Also, I noticed my bank account number recently changed. (previous number I believe was 77417, now it's 69547....)

What's weird is that when I give people my contact information, my old bank account (77417... I think?) is still being stored with my contact info.... but neither bank accounts actually give me money when someone tries paying me.

This started occurring maybe last night, def all day today.

Had another friend test with his friends- he said no one was able to recieve their $1 transactions they were testing with 

**To Reproduce**
[Steps to reproduce the bug]
1. Use phone to send money to bank account
2. Attempt to send money to either of those bank accounts
2. no workie :(
3. 

**Expected behavior**
receiving money via Bank app.... also only having one bank account #, and it being 

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
Bank account numbers were recently switched to fix unintended duplicates. The new numbers are what should be used. It should be 5 digits. (The banking screen may show a longer version that is fixed in an upcoming update, but should still work if you use the last 5 digits. I can look and see if the phone is saving the wrong number still under contacts.

**Comment by xXJamieXx** [comment]
Fixed in live server.
