### ISSUE TITLE
[BUG] Playtime not counting

### ISSUE THREAD

**Issue by MxriioV2** [xXJamieXx/paradox-bugs#387]
**Your Discord Name**
Mxriio#2829

**Describe the bug**
I had around 400 hours or more in 2.0 and now in 3.0 i cant get any hours no matter what i try it says 0 and always says 2 hour in current session 

**To Reproduce**
This happened at the start of 3.0 and i never noticed

**Expected behavior**
To see my exact Playtime over all and in a current session 

**Screenshots**
![image_2022-04-13_074248202](https://user-images.githubusercontent.com/103556570/163108291-8f01835a-b54a-4dfa-9301-7aeb3d35cd12.png)

**Logs**
[CitizenFX_log_2022-04-13T053709.log](https://github.com/xXJamieXx/paradox-bugs/files/8478504/CitizenFX_log_2022-04-13T053709.log)

**Comment by xXJamieXx** [comment]
I can't find any account of yours with 400 hours. For the issue with your playtime not counting, there is not enough info here for me to me to determine why its not adding. The log file you linked only shows the initial connection and is not from a full play session to determine if its erroring during the session. If you could attach a log from a full session (connection -> disconnection) it may show where the issue is occuring.

**Comment by xXJamieXx** [comment]
Seems like an isolated issue and haven't heard back or see any other reports so will be closing this now.
